name: Jekyll site CI

on:
  push:
    branches:
      - master # or main, depending on your default branch name

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    # Setup Ruby and cache gems
    - name: Setup Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.1.4' # or the version you prefer

    - name: Cache Gems
      uses: actions/cache@v2
      with:
        path: vendor/bundle
        key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
        restore-keys: |
          ${{ runner.os }}-gems-

    # Install dependencies
    - name: Install Gems
      run: |
        bundle config set path 'vendor/bundle'
        bundle install --jobs 4 --retry 3

    # Build your site
    - name: Build Jekyll site
      run: bundle exec jekyll build

    # Optional step: Run tests here if you have any

    # Deploy to GitHub Pages
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./_site  # or the directory where Jekyll builds your site


